### ISSUE TITLE
Adding requirement.txt

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/Open-LLM#2]
While setting up the project, it gives giving error 
<img width="1440" alt="image" src="https://github.com/glific/Open-LLM/assets/40158831/a20c0f89-1584-4ee1-9a67-a1846c3647ca">

Looks like the issue with the dependency, but there is no requirement.txt file

**Comment by EdmundKorley** [comment]
Per the README, the project is using pipenv instead of requirements.txt. So run install pipenv, run `pipenv shell`, then `pipenv install`. See README for full instructions.
