### ISSUE TITLE
MVP for llm4dev in Glific

### ISSUE THREAD

**Issue by mahajantejas** [glific/Open-LLM#30]
1. Referencing specific knowledge bases at node level by introducing category in `embedding` table
2. Ability for NGO staff to add different system prompts at node level within the flows
3. Change the api param name from`prompt` to `question`
4. Monitor how many API calls made (at the org level) to the repo and how many successful / unsuccessful response sent back 
5. File management APIs for OpenLLM added knowledgebase documents

**Comment by Ishankoradia** [comment]
- [x] Ability to add system prompts at node level 
- [x] Change api param from `prompt` to `question`
- [x] File management apis for openLLM
    - [x] Api to add category POST `/api/knowledge/category`
    - [x] Api to delete category POST `/api/knowledge/category/{category_uuid}`
    - [x] Api to get all categories GET `/api/knowledge/category/get`
    - [x] Api to get all org documents GET `/api/files`
    - [x] Api to delete a document and its embeddings DELETE `/api/files/:file_uuid`
    - [x] Update the current api `api/upload` to accept a `category_uuid`. Map the file and embedding to this category
- [x] Update the endpoint `/api/chat` to accept knowledge base category i.e. `category_uuid`
