### ISSUE TITLE
Conversational Ability

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/Open-LLM#9]
**Is your feature request related to a problem? Please describe.**
Enhancing the chat's capability to remember past questions from each user, helps generate more context-aware and efficient answers, reducing the chance of generating incorrect information.

**Additional context**
Here are a few resources
- [A better way to prompt LLMs in Elixir](https://www.charlieholtz.com/articles/elixir-ai?utm_medium=email&utm_source=elixir-radar)
- [Chat completions API](https://platform.openai.com/docs/guides/gpt/chat-completions-api)

**Comment by EdmundKorley** [comment]
This is already functional you just need to pass in a session id per the README

https://github.com/glific/Open-LLM/blob/0f2552c87e3fa5cfeb5c436f07ff4b447d34a5e7/README.md?plain=1#L92-L118
